### PR TITLE
Input shaping menu shows X frequency for Y

### PR DESCRIPTION
**Pull request by KimmoHop**
### Description

Fixes showing Y frequency in input shaping menu

### Related Issues

https://github.com/classicrocker883/MriscocProUI/issues/21

### CODE REVIEW

**Comment by Lord-Memester** [comment]
Oh! So that's where I edit dwin.cpp. Thanks for your unintended helping me out! (And also your intended help. I haven't ventured into input shaping yet, but it's good to know that if I do it won't be impossible to understand.)

**Comment by classicrocker883** [comment]
hey nice catch. I'll relay the information over to Mriscoc. I'll have this fixed for next update. but if anyone is looking to have the correct values, I believe you can set them via Gcode commands rather than through the LCD UI screen.

**Comment by KimmoHop** [comment]
The value is editable in UI and will show correct value until you back out to previous menu. I also haven't flashed it after I saw in terminal that correct value is saved (and most likely used ;) ) in EEPROM.

I was on the edge to which repository make the fix :) This seemed to be closer to stock Marlin in latest commits.

**Review by classicrocker883 — APPROVED** [review]

**Comment by Lord-Memester** [comment]
Why's this still show as an open PR?

**Comment by classicrocker883** [comment]
> Why's this still show as an open PR?

I'm not very familiar with the all these functions like merge and pull and push. I edited it manually, mainly so I know it's done correctly. but I made a comment in an update showing the change was made.

**Pull request closed without merging**
