### PR TITLE
Add support for Aquila X3

### PR DESCRIPTION
**Pull request by gcardoso22**
### Description
Adds support for Aquila X3 and fixes a bug in M48 that assumed BL Touch was always present

### Requirements
Voxelab Aquila X3

### Benefits
Adds support for a new printer

### Related Issues
#70

### CODE REVIEW

**Comment by classicrocker883** [comment]
thank you so much for writing up this configuration. I am currently working on the next Update release for September. So it may be some time for the next release. but I will add this PR. If you are using the current default repo branch of `2023-August`, I advise caution for now because I am working on it and suggest use either an earlier "commit", or the `tag` of the newest Release (not of HC32 because that is a different branch altogether).

**Comment by gcardoso22** [comment]
I used the default 2023-August branch

**Comment by classicrocker883** [comment]
@gcardoso22 I was wondering, does the X3 use GD32 for chip, or something else?

**Comment by gcardoso22** [comment]
The X3 uses N32 chip (at least mine does)

image

**Pull request merged**
